// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_4VX0t3mO3YKw5hX-vvar_riFD3vj9jc',
    appId: '1:146199599359:web:56b629969ed9afe89094ca',
    messagingSenderId: '146199599359',
    projectId: 'fir-demo-c9773',
    authDomain: 'fir-demo-c9773.firebaseapp.com',
    storageBucket: 'fir-demo-c9773.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_ZaEvvVzjKGh__g0I_xwxOjMTbO-gs30',
    appId: '1:146199599359:android:7c09a5ea04d51d9f9094ca',
    messagingSenderId: '146199599359',
    projectId: 'fir-demo-c9773',
    storageBucket: 'fir-demo-c9773.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJzm-tyilj0H9ouEtqf0qnSfz-8C4sRZQ',
    appId: '1:146199599359:ios:bd7d52edda52f9169094ca',
    messagingSenderId: '146199599359',
    projectId: 'fir-demo-c9773',
    storageBucket: 'fir-demo-c9773.appspot.com',
    iosClientId: '146199599359-6ddhnkuo2j59uuvgc0evm69n4dv582kn.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseDemo',
  );
}
